export const USER_FETCH_ME = "USER_FETCH_ME";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_META_FETCHING = "USER_META_FETCHING";
export const USER_META_FETCH_SUCESS = "USER_META_FETCH_SUCESS";
export const USER_META_FETCH_ERROR = "USER_META_FETCH_ERROR";
